apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: image-updater-test=gcr.io/gcp-poc-321808/tokko-certifier
    argocd-image-updater.argoproj.io/image-updater-test.update-strategy: latest
    # argocd-image-updater.argoproj.io/image-updater-test.allow-tags: regexp:^test*
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argo-ns/github-repo-creds
  name: image-updater-test
  namespace: argo-ns
spec:
  project: default
  source:
    repoURL: https://github.com/jitheshkv/image-updater-test
    targetRevision: master
    path: application/
  destination:
    server: https://kubernetes.default.svc
    namespace: asher
  syncPolicy:
    automated:
      prune: true
      selfHeal: true